[app]

# (str) Título do aplicativo
title = Abastecimento3A

# (str) Nome do pacote
package.name = abastecimento3a

# (str) Domínio do pacote
package.domain = org.abastecimento

# (str) Pasta onde está o código principal
source.dir = .

# (str) Extensões incluídas
source.include_exts = py,png,jpg,jpeg,kv,atlas,json,txt

# (str) Versão do aplicativo
version = 1.0

# (list) Dependências Python
requirements = python3,kivy

# (str) Orientação
orientation = portrait

# (bool) Tela cheia
fullscreen = 0

# (str) Arquivo principal
source.main = main.py


# (str) Preservar o espaço reservado do app
# presplash.filename = %(source.dir)s/data/presplash.png

# (str) Ícone
# icon.filename = %(source.dir)s/data/icon.png


[buildozer]

# (str) Diretório onde o Buildozer guarda os arquivos
log_level = 2

# (str) Diretório de trabalho
warn_on_root = 1

# (str) Caminho do build
build_dir = .buildozer

# (str) Diretório dos APKs
bin_dir = bin
